In [16]:
import pandas as pd
import numpy as np

In [17]:
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [18]:
df=pd.read_csv("survey.csv")

In [19]:
df.iloc[200]

Age                                          27
Gender                                   Female
Self Employed                                No
family history of mental health             Yes
Prior Treatment                             Yes
Work Pressure                         Sometimes
Sleep                                         7
Remote Work                                  No
Tech company                                Yes
Social Status                            Middle
Caretakers available                         No
Will you seek help                           No
leave                                 Very easy
supervisor                         Some of them
Mental health data taken                     No
Physical health data taken                   No
Output                                        3
Name: 200, dtype: object

In [20]:
df['Gender'].value_counts()

Male           354
Female          82
Gay             24
Lesbian         22
Transgender      9
Bisexual         8
Male             1
Name: Gender, dtype: int64

In [21]:
df.isnull().sum()
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
df['Self Employed']=enc.fit_transform(df['Self Employed'])
df['Work Pressure']=enc.fit_transform(df['Work Pressure'])
df['Gender']=enc.fit_transform(df['Gender'])
df['family history of mental health']=enc.fit_transform(df['family history of mental health'])
df['Prior Treatment']=enc.fit_transform(df['Prior Treatment'])
df['Remote Work']=enc.fit_transform(df['Remote Work'])
df['Tech company']=enc.fit_transform(df['Tech company'])
df['Social Status']=enc.fit_transform(df['Social Status'])
df['Caretakers available']=enc.fit_transform(df['Caretakers available'])
df['Will you seek help']=enc.fit_transform(df['Will you seek help'])
df['leave']=enc.fit_transform(df['leave'])
df['supervisor']=enc.fit_transform(df['supervisor'])
df['Mental health data taken']=enc.fit_transform(df['Mental health data taken'])
df['Physical health data taken']=enc.fit_transform(df['Physical health data taken'])
print('Size has been converted to numeric values')

Size has been converted to numeric values


In [22]:
df['Self Employed'].fillna(df['Self Employed'].mean(),inplace=True)
df['Work Pressure'].fillna(df['Work Pressure'].mean(),inplace=True)


In [23]:
df.isnull().sum()

Age                                0
Gender                             0
Self Employed                      0
family history of mental health    0
Prior Treatment                    0
Work Pressure                      0
Sleep                              0
Remote Work                        0
Tech company                       0
Social Status                      0
Caretakers available               0
Will you seek help                 0
leave                              0
supervisor                         0
Mental health data taken           0
Physical health data taken         0
Output                             0
dtype: int64

In [24]:
df

Age  Gender  Self Employed  family history of mental health  \
0     37       1              2                                0   
1     44       3              2                                0   
2     32       4              2                                0   
3     31       4              2                                1   
4     31       4              2                                0   
..   ...     ...            ...                              ...   
495   32       4              0                                0   
496   32       4              0                                0   
497   37       4              0                                0   
498   39       3              0                                0   
499   31       4              0                                0   

     Prior Treatment  Work Pressure  Sleep  Remote Work  Tech company  \
0                  1              1      6            0             1   
1                  0              2      7            0             0   
2                  0              2     10            0             1   
3                  1              1      5            0             1   
4                  0              0      9            1             1   
..               ...            ...    ...          ...           ...   
495                0              4     10            0             1   
496                1              3      6            0             0   
497                0              4      7            0             1   
498                0              4      9            1             0   
499                0              4      8            0             1   

     Social Status  Caretakers available  Will you seek help  leave  \
0                0                     1                   2      2   
1                0                     0                   0      0   
2                2                     0                   1      1   
3                1                     2                   1      1   
4                2                     0                   0      0   
..             ...                   ...                 ...    ...   
495              1                     0                   1      0   
496              1                     2                   1      4   
497              2                     0                   1      2   
498              0                     2                   1      3   
499              0                     0                   0      0   

     supervisor  Mental health data taken  Physical health data taken  Output  
0             2                         1                           0       2  
1             0                         1                           1       3  
2             2                         2                           2       2  
3             0                         0                           0       1  
4             2                         2                           2       3  
..          ...                       ...                         ...     ...  
495           0                         1                           2       3  
496           2                         1                           1       3  
497           1                         1                           0       2  
498           0                         1                           0       2  
499           0                         1                           1       3  

[500 rows x 17 columns]

In [25]:
df

Age  Gender  Self Employed  family history of mental health  \
0     37       1              2                                0   
1     44       3              2                                0   
2     32       4              2                                0   
3     31       4              2                                1   
4     31       4              2                                0   
..   ...     ...            ...                              ...   
495   32       4              0                                0   
496   32       4              0                                0   
497   37       4              0                                0   
498   39       3              0                                0   
499   31       4              0                                0   

     Prior Treatment  Work Pressure  Sleep  Remote Work  Tech company  \
0                  1              1      6            0             1   
1                  0              2      7            0             0   
2                  0              2     10            0             1   
3                  1              1      5            0             1   
4                  0              0      9            1             1   
..               ...            ...    ...          ...           ...   
495                0              4     10            0             1   
496                1              3      6            0             0   
497                0              4      7            0             1   
498                0              4      9            1             0   
499                0              4      8            0             1   

     Social Status  Caretakers available  Will you seek help  leave  \
0                0                     1                   2      2   
1                0                     0                   0      0   
2                2                     0                   1      1   
3                1                     2                   1      1   
4                2                     0                   0      0   
..             ...                   ...                 ...    ...   
495              1                     0                   1      0   
496              1                     2                   1      4   
497              2                     0                   1      2   
498              0                     2                   1      3   
499              0                     0                   0      0   

     supervisor  Mental health data taken  Physical health data taken  Output  
0             2                         1                           0       2  
1             0                         1                           1       3  
2             2                         2                           2       2  
3             0                         0                           0       1  
4             2                         2                           2       3  
..          ...                       ...                         ...     ...  
495           0                         1                           2       3  
496           2                         1                           1       3  
497           1                         1                           0       2  
498           0                         1                           0       2  
499           0                         1                           1       3  

[500 rows x 17 columns]

In [26]:
x=df.drop(columns='Output')
y=df['Output']

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [28]:
print(x_train.shape,x_test.shape,y_train.shape)

(400, 16) (100, 16) (400,)


In [29]:
import xgboost as xgb

In [30]:
xgb_crop= xgb.XGBClassifier(learning_rate=0.5,n_estimators=150,objective='multi:softprob',random_state=12,gamma=280)

In [31]:
xgb_crop.fit(x_train.values,y_train.values)

E:\anaconda\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[22:09:00] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=280, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.5, max_delta_step=0,
              max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=150, n_jobs=8,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto',
              random_state=12, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [32]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [33]:
y_pred=xgb_crop.predict(x_test.values)

In [34]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0, 22],
       [ 0,  0, 36],
       [ 0,  0, 42]], dtype=int64)

In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        22
           2       0.00      0.00      0.00        36
           3       0.42      1.00      0.59        42

    accuracy                           0.42       100
   macro avg       0.14      0.33      0.20       100
weighted avg       0.18      0.42      0.25       100



E:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
from sklearn.ensemble import RandomForestClassifier
rdf_clf=RandomForestClassifier(criterion='entropy',n_estimators=200,n_jobs=-1,random_state=12)
rdf_clf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200, n_jobs=-1,
                       random_state=12)

In [37]:
y_pred_rf=rdf_clf.predict(x_test)

In [38]:
print(confusion_matrix(y_test,y_pred_rf))

[[11  6  5]
 [ 4 14 18]
 [ 5 12 25]]


In [39]:
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           1       0.55      0.50      0.52        22
           2       0.44      0.39      0.41        36
           3       0.52      0.60      0.56        42

    accuracy                           0.50       100
   macro avg       0.50      0.49      0.50       100
weighted avg       0.50      0.50      0.50       100



In [40]:
print(accuracy_score(y_pred_rf,y_test))

0.5


In [41]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy',random_state=12,max_depth=5)
dt

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=12)

In [42]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=12)

In [43]:
y_pred_dt=dt.predict(x_test)

In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        22
           2       0.00      0.00      0.00        36
           3       0.42      1.00      0.59        42

    accuracy                           0.42       100
   macro avg       0.14      0.33      0.20       100
weighted avg       0.18      0.42      0.25       100



E:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [56]:
from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(n_estimators=200)
random_forest_classifier = random_forest_model.fit(x_train,y_train)

In [57]:
import sklearn
y_pred_randomforest = random_forest_model.predict(x_test)
print("Random Forest Clasifier Train Accuracy : {} %".format(random_forest_classifier.score(x_train,
                                                                                            y_train)*100))
print("\nRandom Forest Clasifier Test Accuracy : {} %".format(sklearn.metrics.accuracy_score(y_test, 
                                                                                     y_pred_randomforest)*100))
print("-------------------------------------------------------------------------------------------------")
print("\nClassification Report : \n {}".format(sklearn.metrics.classification_report(y_test, 
                                                                                     y_pred_randomforest)))
print("-------------------------------------------------------------------------------------------------")
print("\n Confusion Matrix :- \n{}".format(sklearn.metrics.confusion_matrix(y_test, 
                                                                           y_pred_randomforest)))

Random Forest Clasifier Train Accuracy : 100.0 %

Random Forest Clasifier Test Accuracy : 60.0 %
-------------------------------------------------------------------------------------------------

Classification Report : 
               precision    recall  f1-score   support

           1       0.67      0.55      0.60        22
           2       0.53      0.53      0.53        36
           3       0.63      0.69      0.66        42

    accuracy                           0.60       100
   macro avg       0.61      0.59      0.60       100
weighted avg       0.60      0.60      0.60       100

-------------------------------------------------------------------------------------------------

 Confusion Matrix :- 
[[12  7  3]
 [ 3 19 14]
 [ 3 10 29]]


In [58]:
x_test.values

array([[35,  4,  0, ...,  1,  1,  1],
       [27,  4,  0, ...,  2,  1,  1],
       [42,  4,  0, ...,  2,  1,  0],
       ...,
       [30,  4,  0, ...,  0,  1,  1],
       [31,  4,  0, ...,  2,  1,  0],
       [39,  2,  0, ...,  0,  1,  1]], dtype=int64)

In [59]:
a=random_forest_model.predict([[37,1,2,0,1,1,6,0,1,0,1,2,2,2,1,0]])
a

array([2], dtype=int64)

In [61]:
import pickle
pickle.dump(rdf_clf, open('model.pkl','wb'))


In [62]:
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[37,1,2,0,1,1,6,0,1,0,1,2,2,2,1,0]]))

[2]


In [63]:
import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle

app = Flask(__name__)
model = pickle.load(open('model.pkl', 'rb'))

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():

    int_features = [int(x) for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction = model.predict(final_features)

    output = round(prediction[0], 2)

    return render_template('index.html', prediction_text='Sales should be $ {}'.format(output))

@app.route('/results',methods=['POST'])
def results():

    data = request.get_json(force=True)
    prediction = model.predict([np.array(list(data.values()))])

    output = prediction[0]
    return jsonify(output)

if __name__ == "__main__":
    app.run(debug=True)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: on


 * Restarting with windowsapi reloader


SystemExit: 1

E:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:3445: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
